### ISSUE TITLE
別名（Alias）功能

### ISSUE THREAD

**Issue by rileychh** [NTUT-NPC/shorts#5]
有時候會希望多個不同的網址被重新導向到同一個位置，這個時候有別名（Alias）功能可以派上用場。

例如，有個 `discord` 重新導向到社團的 Discord 伺服器邀請：

```toml
[temporary]
"discord" = "https://discord.gg/9yYtgA4HXz"
```

如果希望 `dc` 和 `doscord` 等等名字也能導向到這個連結，我們可以新增別名

```toml
[aliases]
"discord" = ["dc", "doscord"]
```
